import { CircleHelp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';

export function AdvertisingHelp() {
  return <Dialog><DialogTrigger asChild><Button variant="outline"><CircleHelp />Como usar o painel</Button></DialogTrigger><DialogContent className="max-h-[85svh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Como usar o painel de anúncios</DialogTitle><DialogDescription>Cadastre uma campanha e escolha onde ela aparece no fórum.</DialogDescription></DialogHeader>
    <div className="space-y-6 text-sm leading-relaxed">
      <section className="space-y-3"><h2 className="text-lg font-semibold">Ligar ou desligar todos os anúncios</h2><p>Use o botão da área <strong>Publicidade no site</strong> para interromper ou retomar a exibição nos três espaços.</p><p>Os cadastros, datas e pausas individuais ficam preservados. Ao habilitar novamente, uma campanha pausada ou encerrada continua sem aparecer.</p><p>A escolha fica salva no servidor. Um anúncio já aberto pode permanecer até a próxima consulta de rotação.</p></section>
      <section className="space-y-3"><h2 className="text-lg font-semibold">1. Cadastre o primeiro anúncio</h2><ol className="list-decimal space-y-2 pl-5"><li>Clique em <strong>Novo anúncio</strong> e preencha empresa, título, descrição e site de destino.</li><li>Envie uma imagem PNG, JPG ou WebP de até 2 MB ou informe o link da imagem. Você pode salvar sem imagem.</li><li>Marque onde exibir e deixe a <strong>Prioridade de rotação</strong> em <strong>1</strong> para começar.</li><li>Confira o início e o término. O término pode ficar vazio.</li><li>Marque <strong>Habilitar campanha no período escolhido</strong>, confira a prévia e clique em <strong>Salvar anúncio</strong>.</li></ol><p className="rounded-lg border bg-muted/30 p-3">Se você não marcar a opção de habilitar, o anúncio será salvo como <strong>Pausado</strong>.</p></section>
      <section className="space-y-3"><h2 className="text-lg font-semibold">2. Escolha onde exibir</h2><ul className="list-disc space-y-2 pl-5"><li><strong>Lista do fórum</strong> aparece entre as conversas do Início. A lista precisa ter pelo menos uma conversa.</li><li><strong>Conversas do fórum</strong> aparece dentro de um tópico, antes da área de comentários.</li><li><strong>Discussões de Estudar</strong> aparece na discussão de um item de Estudar, quando há uma conversa disponível.</li></ul><p>Você pode marcar mais de um espaço. As empresas apoiadoras do Início e de Sobre são uma apresentação separada.</p></section>
      <section className="space-y-3"><h2 className="text-lg font-semibold">3. Entenda as vagas e a troca</h2><p><strong>Cinco vagas não são cinco anúncios aparecendo juntos.</strong> Cada bloco mostra apenas um anúncio por vez.</p><p>As vagas limitam quantas campanhas podem participar daquele espaço no mesmo período. Os agendamentos futuros também respeitam o limite.</p><p><strong>Máximo de cadastros</strong> conta todos os anúncios guardados no painel, inclusive pausados e encerrados.</p><p><strong>Rotação em segundos</strong> define o intervalo até a próxima seleção enquanto o espaço está visível. O valor inicial é 45 segundos.</p><p>Com uma campanha, ela continua no espaço. Com duas, elas se alternam. Com três ou mais, a prioridade influencia a próxima escolha.</p><p>Comece com prioridade 1. Um valor maior aumenta as chances entre as alternativas, sem garantir uma porcentagem de exibição.</p></section>
      <section className="space-y-3"><h2 className="text-lg font-semibold">4. Confira o estado</h2><ul className="list-disc space-y-2 pl-5"><li><strong>Pausado</strong> está desabilitado.</li><li><strong>Agendado</strong> está habilitado, mas o início ainda não chegou.</li><li><strong>Em exibição</strong> pode ser escolhido nos espaços marcados.</li><li><strong>Encerrado</strong> já passou da data de término.</li></ul><p>Se uma campanha encerrada precisar voltar, edite o término. Habilitar sozinho não altera as datas.</p></section>
      <section className="space-y-3"><h2 className="text-lg font-semibold">5. Faça um teste</h2><p>Crie um anúncio com início em um horário que já passou. Escolha <strong>Lista do fórum</strong> e marque a opção de habilitar.</p><p>Depois de salvar, confira se está <strong>Em exibição</strong>. Abra o Início e procure o bloco Publicidade entre as conversas.</p><p>Se aparecer outra empresa, espere a troca com o bloco visível. A prévia do cadastro não soma exibições ou cliques.</p></section>
      <section className="space-y-3"><h2 className="text-lg font-semibold">6. Acompanhe e altere</h2><p>Uma exibição conta quando pelo menos metade do anúncio fica visível por um segundo, com a aba aberta.</p><p>Um clique conta quando alguém abre o site pela imagem ou pelo botão. Os totais não são pessoas únicas.</p><p>Use o botão de atualizar para consultar os números mais recentes.</p><p>O lápis edita a campanha. <strong>Pausar</strong> mantém os dados. A lixeira exclui o cadastro e os contadores após sua confirmação.</p><p>Os dados ficam salvos no servidor e sobrevivem a reinicializações. Enviar um commit não transfere as campanhas para outra hospedagem.</p></section>
    </div><DialogFooter><DialogClose asChild><Button>Entendi</Button></DialogClose></DialogFooter>
  </DialogContent></Dialog>;
}
