import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Compass, Github, Map, Moon, Search, Sparkles, Sun, Users, Video, Route, Code2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { categories, labels, normalize, pageInfo, resourcePath, resources, taxonomy, type Resource } from './catalog';

const icons = [Users, BookOpen, Route, Sparkles, Video];
const repositoryValue = import.meta.env.VITE_DATA_REPOSITORY || 'https://github.com/LucasPedruo/guia-da-ti-dados';
const repository = /^https:\/\/github\.com\/[\w.-]+\/[\w.-]+\/?$/.test(repositoryValue) ? repositoryValue.replace(/\/$/, '') : '';

function ResourceCard({ resource }: { resource: Resource }) {
  const category = categories.find(c => c.id === resource.type)!;
  return <article className="resource-card"><div className="card-top"><span className="resource-mark"><Code2 size={22} /></span><span className="eyebrow">{category.name}</span></div><h3><a href={resourcePath(resource)}>{resource.name}<ArrowUpRight size={18} /></a></h3><p>{resource.summary}</p><div className="tags">{resource.areas.map(area => <a key={area} href={`/areas/${area}`}>{labels[area] || area}</a>)}</div>{resource.demo && <small>Cadastro fictício · demonstração</small>}</article>;
}

export function App({ path }: { path: string }) {
  const page = pageInfo(path);
  const [query, setQuery] = useState('');
  const [type, setType] = useState(page.category?.id || '');
  const [dark, setDark] = useState(false);
  useEffect(() => {
    try { setDark(localStorage.getItem('theme') === 'dark'); } catch { /* Storage may be unavailable. */ }
    setQuery(new URLSearchParams(window.location.search).get('q') || '');
  }, []);
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); }, [dark]);
  function toggleTheme() { const next = !dark; setDark(next); try { localStorage.setItem('theme', next ? 'dark' : 'light'); } catch { /* Optional preference. */ } }
  const tokens = normalize(query).trim().split(/\s+/).filter(Boolean);
  const filtered = resources.filter(r => (!type || r.type === type) && (!page.area || r.areas.includes(page.area)) && (!page.technology || r.technologies.includes(page.technology)) && tokens.every(token => normalize([r.name, r.summary, r.description, ...r.areas, ...r.technologies, ...r.languages].join(' ')).includes(token)));
  const home = path === '/';
  return <><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><header className="site-header"><a className="brand" href="/"><span><Compass size={24} /></span>guia<span className="brand-light">da</span>ti<span className="brand-dot">.</span></a><nav aria-label="Principal"><a href="/explorar">Explorar</a><a href="/comunidades">Comunidades</a><a href="/cursos">Aprender</a><a href="/criadores">Criadores</a></nav><div className="header-actions"><Button variant="ghost" size="icon" aria-label={dark ? 'Ativar tema claro' : 'Ativar tema escuro'} onClick={toggleTheme}>{dark ? <Sun /> : <Moon />}</Button><Button asChild variant="outline"><a href="/contribuir"><Github />Contribuir</a></Button></div></header>
  <main id="conteudo">
    {!page.valid ? <section className="page-heading"><p className="eyebrow">404</p><h1>Página não encontrada</h1><Button asChild><a href="/explorar">Explorar recursos</a></Button></section> : path === '/contribuir' ? <section className="detail"><p className="eyebrow">Aberto e colaborativo</p><h1>Um guia feito por todos.</h1><p>Conhece um recurso que merece estar aqui? Ajude outras pessoas a encontrar seu próximo passo.</p><ol><li>Procure pelo recurso para evitar duplicados.</li><li>Adicione ou corrija o cadastro no repositório de dados.</li><li>Envie sua contribuição para revisão da comunidade.</li></ol>{repository ? <Button asChild><a href={`${repository}/blob/main/CONTRIBUTING.md`}><Github />Contribuir no GitHub</a></Button> : <p className="notice">O repositório público ainda está em preparação. As instruções desta versão estão em database/CONTRIBUTING.md.</p>}</section> : page.resource ? <section className="detail"><a className="back" href={`/${page.category!.route}`}>← {page.category!.name}</a><p className="eyebrow">{page.resource.demo ? 'Cadastro fictício de demonstração' : page.category!.name}</p><h1>{page.resource.name}</h1><p className="lead">{page.resource.summary}</p><p className="description">{page.resource.description}</p><div className="tags">{page.resource.technologies.map(t => <a href={`/tecnologias/${t}`} key={t}>{labels[t] || t}</a>)}</div><p>Idiomas: {page.resource.languages.join(', ')}</p><p>Última atualização: {page.resource.updatedAt.split('-').reverse().join('/')}</p><div className="detail-actions"><Button asChild><a href={page.resource.url} target="_blank" rel="noopener noreferrer">Visitar recurso <ArrowUpRight /></a></Button>{repository && <Button asChild variant="outline"><a href={`${repository}/edit/main/data/${page.resource.type}/${page.resource.slug}.json`}>Editar no GitHub</a></Button>}</div></section> : <>
    <section className={home ? 'hero' : 'page-heading'}><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Aberto, comunitário e feito para explorar</p><h1>{home ? <>Seu próximo passo<br />em tecnologia<br /><em>começa aqui.</em></> : page.title}</h1><p className="lead">{page.description}</p><form className="search-box" action="/explorar" role="search"><Search size={21} aria-hidden="true" /><Input name="q" aria-label="Buscar recursos" placeholder="O que você quer descobrir?" value={query} onChange={event => setQuery(event.target.value)} /><Button type="submit" aria-label="Pesquisar"><ArrowRight /></Button></form>{home && <div className="suggestions"><span>Explore:</span>{['react', 'cybersecurity', 'dados'].map(id => <a key={id} href={`/${id === 'react' ? 'tecnologias' : 'areas'}/${id}`}>{labels[id]} <ArrowUpRight size={12} /></a>)}</div>}</div>{home && <div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="art-core"><Compass size={62} strokeWidth={1.3} /><span>ENCONTRE SEU CAMINHO</span></div><span className="floating-card float-one"><Users />Conecte-se</span><span className="floating-card float-two"><Code2 />Descubra</span><span className="floating-card float-three"><BookOpen />Aprenda</span><span className="art-star">✳</span></div>}</section>
    {home && <section className="section-block"><div className="section-title"><div><p className="eyebrow">Muitos caminhos, um só lugar</p><h2>Por onde você quer começar?</h2></div><a href="/explorar">Ver tudo <ArrowRight size={16} /></a></div><div className="category-grid">{categories.map((category, index) => { const Icon = icons[index]; return <a href={`/${category.route}`} className="category-card" key={category.id}><Icon size={25} /><h3>{category.name}</h3><p>{category.description}</p><ArrowUpRight className="category-arrow" size={18} /></a>; })}</div></section>}
    <section className="section-block catalog-section"><div className="section-title"><div><p className="eyebrow">Conhecimento que circula</p><h2>{home ? 'Descubra novas possibilidades' : 'Recursos para explorar'}</h2></div><span aria-live="polite">{filtered.length} recursos</span></div><div className="filters" aria-label="Filtrar por categoria">{[{ id: '', name: 'Todos' }, ...categories].filter(c => !page.category || c.id === page.category.id).map(c => <button key={c.id} aria-pressed={type === c.id} className={type === c.id ? 'active' : ''} onClick={() => setType(c.id)}>{c.name}</button>)}</div><p className="demo-notice">Versão em construção. Os cadastros abaixo são exemplos fictícios para demonstrar a navegação.</p>{filtered.length ? <div className="resource-grid">{filtered.map(r => <ResourceCard key={`${r.type}/${r.slug}`} resource={r} />)}</div> : <div className="empty"><Search /><h3>Nenhum recurso encontrado</h3><p>Tente outro termo ou escolha uma categoria diferente.</p><Button variant="outline" onClick={() => { setQuery(''); setType(page.category?.id || ''); }}>Limpar busca</Button></div>}</section>
    {home && <section className="community-banner"><span className="banner-icon"><Map size={36} /></span><div><p className="eyebrow">Ninguém cresce sozinho</p><h2>Encontre pessoas no mesmo caminho.</h2><p>Explore comunidades para trocar experiências e aprender junto.</p></div><Button asChild><a href="/comunidades">Conhecer comunidades <ArrowRight /></a></Button></section>}
    <section className="section-block"><p className="eyebrow">Tecnologia vai além do código</p><h2>Explore por área</h2><div className="area-links">{taxonomy.areas.map(area => <a key={area} href={`/areas/${area}`}>{labels[area] || area}<ArrowUpRight size={14} /></a>)}</div></section></>}
  </main><footer><a className="brand" href="/">guiadati.</a><p>Conhecimento aberto. Caminhos compartilhados.</p><a href="/contribuir">Ajude a construir o guia <ArrowUpRight size={15} /></a></footer></>;
}
